### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [wheitkoetter/AutoGridComp#1]
# Problem
Please remove .pyc files they are generated on the install of the plugin

**Comment by wheitkoetter** [comment]
Thanks for the advise. The .pyc files were deleted and the code has been uploaded again to the QGIS plugin repository under the version name 0.2.

**Comment by NyakudyaA** [comment]
Please also consider adding a homepage to the metadata.txt. If you do not have one you can just point to the repo link

![homepage](https://user-images.githubusercontent.com/2510900/65956214-27536380-e44a-11e9-822a-d7514f5397fa.png)
@wheitkoetter
